name: emergencyapp
description: Emplyee Emergency App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  http: 0.12.2
  move_to_background: ^1.0.2
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.3

dependency_overrides:
  flutter_offline: 0.2.4+1
  connectivity: ^0.4.3+6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


